sudo: required
services:
    - docker

before install:
    - docker build -t adnadn/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true adnadn/react-test npm test

after_sucess:
    - docker build -t adn888/multi-client ./client
    - docker build -t adn888/multi-nginx ./nginx   
    - docker build -t adn888/multi-server ./server   
    - docker build -t adn888/multi-worker ./worker   
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin    
    #Take those images and push to dockerhub
    - docker push adnadn/multi-client 
    - docker push adnadn/multi-nginx 
    - docker push adnadn/multi-server 
    - docker push adnadn/multi-worker 

